# Generated by Django 3.1.3 on 2020-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0002_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='tech',
            field=models.ManyToManyField(max_length=50, to='port_app.Tech'),
        ),
    ]
