# Generated by Django 3.1.3 on 2020-11-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0003_auto_20201117_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='projects',
            name='tech',
            field=models.ManyToManyField(blank=True, null=True, to='port_app.Tech'),
        ),
    ]
