# Generated by Django 3.1.3 on 2020-11-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0006_auto_20201117_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='colorNum',
        ),
        migrations.AddField(
            model_name='skills',
            name='colorNum',
            field=models.IntegerField(default=0),
        ),
    ]
