# Generated by Django 3.1.3 on 2020-11-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0008_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tech',
            field=models.ManyToManyField(related_name='children', to='port_app.Tech'),
        ),
    ]
