# Generated by Django 3.1.3 on 2020-12-30 23:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0009_auto_20201118_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
