# Generated by Django 3.1.3 on 2020-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0010_projects_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
